apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:VHpPt/r4qhptQYuJm0vNo8aFJfGO2wrkudr4DDbl+srn5Ji0+MidDg==,iv:xPninT2J2zpzckxGeEj1qWEENLcSP08eyG1kRkHgHv4=,tag:ey5mzGdTeNXvdLfFS9BMQQ==,type:str]
sops:
  age:
    - recipient: age1f62w4qzxmdew8a0tzre2qfmt7khhdgcemjj34qe8dcjulzwtxp6qvaru2e
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzKzBMazd3c1o4R3J6WHNE
        ellmelFFTHFsL2JhRGV1RjNMRTN4RjlHMEhZCjF6TWNVa0NlbHlhY3VDNkE3eFla
        UmsvRHJlSEhFM2tPcXRENDFpRGtGcFEKLS0tIGdYWm9QNE96Q1E4VWpGc1hhcUpG
        REc4cG1NMERUWTA4dHJQeFBpaG9PNncKIfaIOghjvbClMq7eLIzBCRa4D1wDk/j2
        a8b1WDCsOv9w0b2TYyl1XHNxldQqyqnfSz8RwE1ol5i+YZ3T51l3uA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-26T15:59:32Z"
  mac: ENC[AES256_GCM,data:rT9uNCgmoVZDPhygYs86Xm/0fL52z/7BVw66C/6kiOBS6sFnVo6CLu0zh33SQp4DrpcvBbFk8wO3P0B7T4+e1OEWDaGs5NMdx6DtrQorGecB9bcuLhu7hd5LBCNw3e8K9bCz5R0XjZt5w6kveQkJq/hCSeTqcMkzJJk6i0g1S8Y=,iv:tB8ZgZGkaek83/Z/cL/oygZDuGOOQjZNxI16sjhT05A=,tag:rwRxAm8WK4bVZmdqbm8JAg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
