apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:bqxNUQflPm/JvP5qeAb+ukNqBgN/Uzqd+3v2Sv09517uge1YQJTV3A==,iv:nuRrCRo2EJCU7Masqk68CcwPn7O86ctjoJvKm6XXSHk=,tag:bFi50lxr/CEJ3FjA2DdxqQ==,type:str]
sops:
  age:
    - recipient: age1f62w4qzxmdew8a0tzre2qfmt7khhdgcemjj34qe8dcjulzwtxp6qvaru2e
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEN3B1MFQyUnZQaGhTbHhG
        UE0xZ3ErN004TEhvbFVSbFBxRUZrNGV5WWxNCkg5Y3AzNE5RVVQ5akdDeWlmY0dy
        SlFBM0RXa3NrQ2tWU0lGL1ZRTE5zS1kKLS0tIDIrZ054NzNRYUFrQi9CQVVsMTVp
        M1VldFJIMWZhNlhqb2ZZOTROclBQb0EKlLnn4NZPV6i57qY2KtUDubpqp/H7BxxD
        kqW8NWVuvJaWQTMDnxCes0/E3oMTW6r32ZZ5qV7HaqBNCCl3SLyb/g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-25T21:00:18Z"
  mac: ENC[AES256_GCM,data:cDeRq2AznfYjHJs+tpcUHlrQZPtB8V/zymImFzYKSC9NXBGvhUIekS26OCRTmXHLtnWTd5Piwc1kqfzXEFHK/2/sLlm97ksb3yZ/k4Eo6rPwCyZc+tSuM61VzKSRy0DY4fVkhIAecLKKEAIdAADogkwNtVfNia4XcIKR5/foYYI=,iv:jxobxZ/uKhP9VjMnxggbpsUN+QRuFtAJAFrnUWi1Gaw=,tag:h1i1Wh5VrnAVqKnlF/cv5g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
