apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:lQlCntd9Cb9m,iv:LBLGJTj6ixDMX9QJK8EQqcHHDV31eB1XUS2vWh5rqyc=,tag:DE6Ysy/cj1gN7RqIi+48pg==,type:str]
sops:
  age:
    - recipient: age1f62w4qzxmdew8a0tzre2qfmt7khhdgcemjj34qe8dcjulzwtxp6qvaru2e
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdElsWkpjd0ZtbGdHWGp5
        TUQzdm03b1ZRcEY5bTU2T0ZmR05Md1QzT1VvCkJtNzhKemt1S1lwQzRlUjJtTk5F
        eFpFVmFIRlovNTlDZWdGd0ozUUFldzQKLS0tIGJ1ZHdDMGx5UlJ5U2FBOUJ5b3FU
        T3JiVzk2R1lndHpZT3I1WFNtT05XVW8K6l2zuRqxyCgJPXPtuXDOLsnjfUxB0cU3
        ee7n0CzdL/jnqh0jqfc2f0+6oxi02pXtGUJDTsEGmlH3q+0dg1Gl/w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-26T15:59:32Z"
  mac: ENC[AES256_GCM,data:1o4Mh1zVTMOtbntcIs41tcQdGthekUKnvcaZQyJwphHJhYE71DSf8QC/nrUysBymu8fKneAXZHR/DT39tchYCHHiR6+53/k6YkT/bSzVtBVhHMExql2o7TCVApE4n4aPLSyAVnFSutuKZdLYgAl8IDeP7Q92MtSr0QuiYnUfcws=,iv:1r6o2AibJU/bjWD2jVxH+rGT+LR3MdLfE8JmArB/PQ4=,tag:uqSTyaQPq/OEjl0IjaCtNg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
