apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:r+XYo6GSCQ6q,iv:0ITubjB+cvVvUleQCZb9w0D9Dj7nyZ/s8/Cc/TUcaEk=,tag:EHCNSVtS86O9iG5XXY8VLQ==,type:str]
sops:
  age:
    - recipient: age1f62w4qzxmdew8a0tzre2qfmt7khhdgcemjj34qe8dcjulzwtxp6qvaru2e
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbitPSHIyNDRPZWNaVFc3
        OHpQMnNHME9CT0cxeEF1bVpMOEUvWU1BWENvClplZTBaTVlIc3RONXRhME5TemRs
        Q3VyU05NWFg2alFaS1Y4bEZ3YmRuUVUKLS0tIDMxQVJadkwxUE1aQXdrWS8rYm9n
        dEJJVVhJVncxWTV1SU5kL2U3Q2VJTGMK7KBaqEZIA5BGAJ8jS9Ykg/frg7gAoeMZ
        xOUJT905rFGM5mWiG6913GAFqPLNXTng/fTtB4v1D/MP1po5DEqdeQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-25T21:00:19Z"
  mac: ENC[AES256_GCM,data:9m4JFGwcxBZVV82E3Ri3/4mJv9W4oDTxxKI0hOcCRsY1/b2V0kb2aaAI4PnuaB2xLtbs3j8BvFQuWpSX5Fps31HOrT2uZpn83feKfh7t/ZZJ/LipdpunjEHeprmMkXK/lVZw3XIOut7WKWfgUwHZLRBynAi3/R5vyKCHk2gDeAA=,iv:XWOay4B+n41Ol6jIo6822CDHu1vbwe80qZFuRlRMCmc=,tag:JM9yM38Oghlz3PhfsJButg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
