apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ""
sops:
  age:
    - recipient: age1f62w4qzxmdew8a0tzre2qfmt7khhdgcemjj34qe8dcjulzwtxp6qvaru2e
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSzFtb2pnWGsyYWpTZ0ZW
        dVlITUZhbTlhVGtUVi9PeCswZHZBUDRNOFhzCkptTWZuN3hUL1haSFp6bjhNdnU5
        ZnpmY1RxbDNNVHNYZHVva3JtNEdRTzgKLS0tIFJLMWdqQ1ROdVBpRXZlbGdxWGRS
        VkpJK3hDOXpJM3AvT0cyWEVPOHU3YVkKallM2G3MgQWEg1BTQ9aGIUZ+xxkEI29k
        fYZCxteMg3IhOGR45vk1s04t+4Z/ekO4xV6ptUMqL6plKWtk8eumLw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-26T15:59:32Z"
  mac: ENC[AES256_GCM,data:g5Sqo5T9j7V73k/8/f1njGyRGwuAqDp51DEMKNSPckI9TYOOVTRzn5937Rat5ikBwgEjJQli6xWhbfJBLKBmXiD5Sxb+dFD1P/vkJ/ZX+HwwCkSiecQrdSFbhUFRrZsc4reAODkwSXPY5PN8SWjTW0GBIANalb78JFnSTLMOJY8=,iv:5hNcrgY4O5qslMUJa1dTqkNxglqQXfRtwDLDFS0I0Tk=,tag:ux0QRBq9HxYSdKabbImq1A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
