apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ""
sops:
  age:
    - recipient: age1f62w4qzxmdew8a0tzre2qfmt7khhdgcemjj34qe8dcjulzwtxp6qvaru2e
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQUNzRSsvSWM0dDNwS3g1
        SGYxTURJY2x6d2xnVC83SUk3aDhZTUhHTzFnCkZHRHhsSk8yWnBrU0dDQWJkc2N0
        amJ1RktkbnMvcWV0eXBEUmVDVlpTREkKLS0tIHhhTWRZNDBXR1gyTElxbVJ0S2t5
        MExnUGdhS1hVSENXaXQ3cEdudndwVjAKeWtooeq2zLmP74h6TbiNuLa8Pku0CF7X
        As8VGw63Uuf0JSD5XwMuFUFKspKKMapZMZrVHqyX6ApgzaRwwCDnRw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-25T21:00:18Z"
  mac: ENC[AES256_GCM,data:f34NMJAewO6/KKpC1NwZVYHW9vExNEvDUUqgrfnW2pqZZ6Elqk1IvUXbUWUyj/g6OLrhngTAHoIwcnfUX7nn+bsBWno/9dYRF2LcDWJKGA3PodwErlLK1o2mibWubKeEyuuAgkGf+Rev7dEO/qdLCfDm96EBffzxFPmgUXB9rhg=,iv:r14kMa5MF+GpkUZXynm7mhWBFKhFDudL6YhOUZ7dzac=,tag:cTCPtsrIywlCMMOYfSfw8Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
