apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:kp8KBeFBBBgqbU3qb6UAPQLyQ8V4aLFDxJQ/MarO5oRhCttaUbkAaPBNrSaiSuMw7jJzcqPmSM3B7E8e2WhBEXfrU6XyuVgamh1KpXI/hjPZGy0nZ91agrlW2gsrs7Dv5dRpW2KguQ02DZBZRZSIXWLsqisy2G1S0nVTDVIgqUgqQkGls+vCe7PwZe6vYQ6kislxu0fSr8Qrft/xR+gZMI0j7cqW6hNDiuNrYbf1ZlcWfnYB,iv:o3+APCOqhEGXj7D3FdeNd+gyNXtkG+AP4uUAbfNvdKM=,tag:bwQbsz8QeN4XJOYIVVy7Fg==,type:str]
sops:
  age:
    - recipient: age1f62w4qzxmdew8a0tzre2qfmt7khhdgcemjj34qe8dcjulzwtxp6qvaru2e
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Sm5XaGJRS1QzbkhUSUth
        cEJlanljUzFjd085dk01NGtQU1BRU2VwZWhNCkF5dUZzQU9FdmNqZTZ4M0JzaHhZ
        NVlOakI0eWk4L3l2dHhpbGkvMlMyTjgKLS0tIDJ0YURhYVcvZ3hmaG0zeXdmZUhq
        dVIvam9MNitaUjA2UjdWQUJGaWpGSTAKtJ93XLl5ytXgd43ulMKx2fnKFk/gRo7F
        neG0nJYqud3veItlQ5iyinPjKW97b3pfPVLlXqMm36Ur4dQ9wYP3iA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-26T15:59:32Z"
  mac: ENC[AES256_GCM,data:IvOj/JqTu0qVacJ3jC8T/jjAjLs+IA23kmS9d41V4zvZ4dc0xsZYGk7fDQZsH5eBbSYt86xBgOlcm8PMAJEjDakrzQdOWsmWhR9AVfrNerWqAeyYG2j+421OJuXqhzi7WJf/rbIgvYIxXkDdT+3Oxgr3l2+LthRE5E6inZATPzs=,iv:kisenUKER0RLimwRxBVKrfYRGOp80ABKtDCg6Jix/wA=,tag:P2eiAw77LYS6fT0ef7Invg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
