apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:B/vd4Y9CXHZ50LQidDRlQ+Rdhh6C/MnLWsaDsKOV00H6Puh5eTs06d5GLftEff0AA6sEeShqkSr70RLAqkoI5323j5qh4snluv7WYDzU05FmIJVfzwNmu/IEU3uZUvrwYymUOcdC48SLHhH2aHhpwuXTAeequVbYnldSUeDH4mowVc2GGT6FC5IZ91/2cULof97u5pI+7o3p+4CQzgjq3Ub1UPikInejZxmWBNHy9tbwXcBi,iv:JBZXHFIlW0Wb/4O5aByIx/4xVFWttBiIJeCSjH0M4dI=,tag:zCFpLXP/IEaxYTarCiePGQ==,type:str]
sops:
  age:
    - recipient: age1f62w4qzxmdew8a0tzre2qfmt7khhdgcemjj34qe8dcjulzwtxp6qvaru2e
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNW16WVdPTkkzamFMaS9y
        RHpUZEJMMWFoY2tiSU5IUHZyMmxGR1E3NlZnCkxaU3BPUzN4NitRT3hzeC96TG1E
        YlNwN0hMbWlaUlIxd0ErNjRjaHZqQk0KLS0tIFNVU1VrV0srOFlyUDN2d3ExNUdG
        MUM3ZVV4RHRXbmI5c2JKZG44YzNxQWcKwHae3ZDpwp1WOFO5/wSoi1F6jcyqZOgd
        tHBIpbl9wGR6+Bq+nlrLQQrCU0bJZAL95TPDUBF9EXJ8rlNeu42VBg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-25T21:00:18Z"
  mac: ENC[AES256_GCM,data:hlQsGsGn8c2VEWfn9I4BsfTW4YegV+ffzULoMU4dDunr3PGTVHOixtNhpy0TBLMd4uAJLMP7jAak44k9zQboI+BfY5zQy/yVS7wk1MCltobVeRVqaiutzu3BL3afQLAO54rigKwUrcmk7211voTa39ZD7U8aNDitEXw3AmZjsUM=,iv:1GYwBNAtn3CQ2StJwl/hYKp/klIuM7RaMmTYbvOxWEo=,tag:lL5HqGXnscpo/SKavx4VMA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
