apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apps/flux-system/namespace.yaml
  - apps/flux-system/ks.yaml
  - apps/kube-system/cilium/ks.yaml
  - apps/kube-system/coredns/ks.yaml